variables:
    RETRY_UTIL_URL: https://github.com/joshdk/retry/releases/download/v1.1.0/retry-linux-amd64.tar.gz
    RETRY_UTIL_HASH: "22139110327fc2a242ed4f5f4ade6e7aa257a25c3002386e15d0badb77469569  /tmp/retry.tar.gz"

stages:
    - install
    - test

.base_php:
    image: sulu/php:8.4-cli
    before_script: &base_php_before_script
        - echo 'memory_limit=-1' >> /usr/local/etc/php/conf.d/zz-custom.ini
        - php -i
        - php -m
        - apt update && apt install -y git
        # install retry util: https://github.com/joshdk/retry
        - wget --output-document /tmp/retry.tar.gz $RETRY_UTIL_URL
        - echo "$RETRY_UTIL_HASH" > /tmp/retry.tar.gz.sha256
        - sha256sum -c /tmp/retry.tar.gz.sha256
        - tar --extract --file /tmp/retry.tar.gz --directory /usr/local/bin retry
        - chmod +x /usr/local/bin/retry

Install:
    stage: install
    extends: .base_php
    before_script:
        - *base_php_before_script
        - mkdir -p ~/.ssh
        - echo $SSH_PRIVATE_KEY_BASE64 > ~/.ssh/id_rsa_base64
        - base64 --decode -i ~/.ssh/id_rsa_base64 > ~/.ssh/id_rsa
        - echo $SSH_PUBLIC_KEY > ~/.ssh/id_rsa.pub
        - chmod 600 ~/.ssh/id_rsa
        - chmod 600 ~/.ssh/id_rsa.pub
        - ssh-keyscan -H gitlab.sulu.io >> ~/.ssh/known_hosts
        - chmod 600 ~/.ssh/known_hosts
        - curl --show-error --silent https://getcomposer.org/installer | php
        - php composer.phar --version
        - php composer.phar config -g cache-dir "$(pwd)/.composer-cache"
    script:
        - php composer.phar install -n --prefer-dist --ignore-platform-reqs --no-scripts
        - php composer.phar dump-autoload --optimize --classmap-authoritative
    artifacts:
        name: "composer-dependencies"
        expire_in: 8 hours
        paths:
            - vendor
            - bin/.phpunit
            - composer.phar
    cache:
        key: "composer"
        paths:
            - .composer-cache/

Test:
    stage: test
    extends: .base_php
    needs:
        - job: Install
          artifacts: true
    script:
        - php composer.phar test -- --testsuite Unit

Lint:
    stage: test
    extends: .base_php
    needs:
        - job: Install
          artifacts: true
    script:
        - php composer.phar lint

Functional:
    stage: test
    extends: .base_php
    needs:
        - job: Install
          artifacts: true
    script:
        - php composer.phar test -- --testsuite Functional

Security Check:
    stage: test
    extends: .base_php
    before_script:
        - curl -sS https://get.symfony.com/cli/installer | bash
        - mv /root/.symfony5/bin/symfony /usr/local/bin/symfony
    script:
        - symfony security:check
    allow_failure: true
